Repository truenas/zettarepl, pull requests merged in 2021-12, with the labels that each got.

#192 NAS-113577 / 22.02-RC.2 / Fix handling of partially replicated snapshots
  integration-tests/replication/test_replicate.py
  zettarepl/replication/most_recent_snapshot.py
  zettarepl/replication/run.py
  zettarepl/replication/snapshots_to_send.py
Labels: jira, backport-13.0

#197 NAS-113397 / 22.02-RC.2 / Make `client_loop: send disconnect: Broken pipe` recoverable replication error
  README.md
  integration-tests/replication/test_replicate.py
  zettarepl/transport/ssh.py
Labels: backport-13.0

#202 NAS-113890 / 22.02 / Fix KeyError: 'naming-schema'
  integration-tests/replication/test_name_regex.py
  zettarepl/replication/task/task.py
Labels: backported, jira, backport-22.02-RC.2

#200 NAS-113441 / 22.02 / Add sbin to path in case of non-privileged user replication
  integration-tests/replication/test_pull_replication.py
  zettarepl/transport/base_ssh.py
  zettarepl/transport/ssh.py
Labels: backport-13.0

#206 NAS-111800 / 22.02 / Perform destination retention before replication in order to free up disk space / quotas
  integration-tests/replication/test_data_progress.py
  integration-tests/replication/test_parallel_replication.py
  integration-tests/replication/test_pre_retention.py
  integration-tests/replication/test_preserves_deleted_datasets.py
  integration-tests/replication/test_progress.py
  integration-tests/replication/test_push_replication.py
  integration-tests/replication/test_replication_retry.py
  integration-tests/replication/test_snapshot_gone.py
  integration-tests/transport/test_ssh_authentication_error.py
  zettarepl/replication/pre_retention.py
  zettarepl/replication/run.py
  zettarepl/replication/snapshots_to_send.py
  zettarepl/replication/task/snapshot_owner.py
  zettarepl/utils/test.py
  zettarepl/zettarepl.py
Labels: backport-13.0
