Repository truenas/zettarepl, pull requests merged in 2023-01, with the labels that each got.

#249 NAS-119605 / 23.10 / sudo
  zettarepl/definition/schema/transport.schema.yaml
  zettarepl/transport/base_ssh.py
  zettarepl/transport/local.py
  zettarepl/transport/progress_report_mixin.py
  zettarepl/transport/ssh.py
Labels: backport-22.12.1

#251 NAS-119994 / 23.10 / Delete ZFS snapshots in chunks of 100
  zettarepl/snapshot/destroy.py
Labels: backport-13.0, backport-22.12.1

#250 NAS-119605 / 22.12.1 / sudo (by themylogin)
  zettarepl/definition/schema/transport.schema.yaml
  zettarepl/transport/base_ssh.py
  zettarepl/transport/local.py
  zettarepl/transport/progress_report_mixin.py
  zettarepl/transport/ssh.py
Labels: skip jira status

#254 NAS-119201 / 23.10 / Expose waiting replication task reason
  zettarepl/observer.py
  zettarepl/zettarepl.py
Labels: backport-13.0, backport-22.12.2
